<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgManifestRoot>$(MSBuildThisFileDirectory)..\</VcpkgManifestRoot>
    <VcpkgManifestInstall>true</VcpkgManifestInstall>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <VcpkgTriplet>x64-windows-static</VcpkgTriplet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='Win32'">
    <VcpkgTriplet>x86-windows-static</VcpkgTriplet>
  </PropertyGroup>
</Project>
